from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from kosmo.contracts.sdd.activity_diagram import DiagramaActividad
    from kosmo.contracts.sdd.document import RichTextDocument
    from kosmo.contracts.sdd.feature import Feature
    from kosmo.contracts.sdd.ids import FeatureId, ProjectId
    from kosmo.contracts.sdd.project import Project


class ProjectRepository(Protocol):
    async def by_id(self, project_id: ProjectId) -> Project | None: ...

    async def by_slug(self, owner_id: str, slug: str) -> Project | None: ...

    async def find_by_slug(self, slug: str) -> Project | None: ...

    async def list_by_owner(self, owner_id: str, *, limit: int = 100) -> list[Project]: ...

    async def save(self, project: Project) -> Project: ...

    async def delete(self, project_id: ProjectId) -> None: ...


class FeatureRepository(Protocol):
    async def by_id(self, feature_id: FeatureId, *, for_update: bool = False) -> Feature | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[Feature]: ...

    async def save(self, feature: Feature) -> Feature: ...

    async def save_many(self, features: list[Feature]) -> list[Feature]: ...

    async def next_number(self, project_id: ProjectId) -> int: ...

    async def delete(self, feature_id: FeatureId) -> None: ...


class DocumentRepository(Protocol):
    async def get_discovery(
        self,
        project_id: ProjectId,
        *,
        for_update: bool = False,
    ) -> RichTextDocument | None: ...

    async def save_discovery(self, project_id: ProjectId, document: RichTextDocument) -> RichTextDocument: ...

    async def delete_discovery(self, project_id: ProjectId) -> None: ...

    async def delete_versions_by_project(self, project_id: ProjectId) -> None: ...

    async def get_requirements(self, feature_id: FeatureId) -> RichTextDocument | None: ...

    async def save_requirements(self, feature_id: FeatureId, document: RichTextDocument) -> RichTextDocument: ...

    async def save_version(
        self,
        project_id: ProjectId,
        phase: object,
        markdown: str,
        change_ids: list[object],
    ) -> str: ...

    async def get_version(self, version_id: str) -> str | None: ...

    async def get_latest_version(self, project_id: ProjectId, phase: object) -> str | None: ...


class RequirementRepository(Protocol):
    async def by_feature_id(self, feature_id: FeatureId, *, for_update: bool = False) -> str | None: ...

    async def save(self, feature_id: FeatureId, markdown: str) -> None: ...

    async def delete(self, feature_id: FeatureId) -> None: ...


class ActivityDiagramRepository(Protocol):
    async def save(self, diagram: DiagramaActividad) -> DiagramaActividad: ...

    async def by_feature_id(self, feature_id: FeatureId, *, for_update: bool = False) -> DiagramaActividad | None: ...

    async def exists(self, feature_id: FeatureId) -> bool: ...

    async def delete(self, feature_id: FeatureId) -> None: ...
